version: '2'
services:

  # RemoteServerService or RemoteOperationCoordinator if enabled
  message-service:
    container_name: message-service
    image: message-service:develop-SNAPSHOT
    environment:
      APP_MAIN: 'data/main-data-coordinator.mjson'
    # Exposed port
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    build:
      context: ./
    volumes:
      - ./data:/usr/src/app/data:ro
      - ./logic:/usr/src/app/logix:ro
      - ./ui:/usr/src/app/ui:ro
      - ./scripts:/usr/src/app/scripts:ro
      
  # DataWorker
  data-service-cli:
    container_name: message-data-service-cli
    image: message-service:develop-SNAPSHOT
    environment:
      APP_MAIN: 'data/main-data-worker.mjson'
    networks:
      - frontend
      - backend
    volumes:
      - ./data:/usr/src/app/data:ro
      - ./logic:/usr/src/app/logix:ro
      - ./ui:/usr/src/app/ui:ro
      - ./scripts:/usr/src/app/scripts:ro
      
  # RawDataWorker
  raw-data-service-cli:
    container_name: message-raw-data-service-cli
    image: message-service:develop-SNAPSHOT
    environment:
      APP_MAIN: 'data/main-raw-data-worker.mjson'
    networks:
      - frontend
      - backend
    volumes:
      - ./data:/usr/src/app/data:ro
      - ./logic:/usr/src/app/logix:ro
      - ./ui:/usr/src/app/ui:ro
      - ./scripts:/usr/src/app/scripts:ro
      
  # ScheduledWorker
  message-cli:
    container_name: message-service-cli
    image: message-service:develop-SNAPSHOT
    networks:
      - frontend
      - backend
    volumes:
      - ./data:/usr/src/app/data:ro
      - ./logic:/usr/src/app/logix:ro
      - ./ui:/usr/src/app/ui:ro
      - ./scripts:/usr/src/app/scripts:ro
    entrypoint: ["node"]
    command: ["cli", "--fetchData", '{ "root": { "prototype": "montage/data/model/data-query", "values": { "criteria": {}, "orderings": [], "prefetchExpressions": null, "typeModule": { "%": "data/descriptors/message.mjson" } } } }']

# Default network
networks:
  frontend:
  backend: